# Generated by Django 6.1 on 2026-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('service', models.CharField(blank=True, default='', help_text="Optional metadata/grouping field, e.g. 'orders'.", max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tool_id'],
            },
        ),
    ]
