# Generated by Django 5.2.7 on 2026-08-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
