# Generated by Django 6.1 on 2026-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_id', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('task_id', models.CharField(blank=True, default='', max_length=100)),
                ('tool_id', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.CharField(blank=True, default='', max_length=100)),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('policy_id', models.CharField(blank=True, default='', max_length=100)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('reason_code', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('latency_ms', models.FloatField(blank=True, help_text='Time spent evaluating this authorization decision, in milliseconds.', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_id', 'timestamp'], name='audit_audit_agent_i_5a88e8_idx'), models.Index(fields=['task_id', 'timestamp'], name='audit_audit_task_id_b50c3e_idx'), models.Index(fields=['decision', 'timestamp'], name='audit_audit_decisio_1394e1_idx')],
            },
        ),
    ]
