# Generated by Django 6.1 on 2026-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('user_scope', models.CharField(blank=True, default='', help_text='Optional. If set, this policy only applies when the authenticated user matches (POLICY_SPEC.md Section 6).', max_length=100)),
                ('allowed_actions', models.JSONField(default=list, help_text="List of action name strings this policy applies to, e.g. ['refund_order'].")),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_mode', models.CharField(choices=[('EXACT', 'Exact'), ('ANY', 'Any'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('resource_ids', models.JSONField(blank=True, default=list, help_text='Used only when resource_mode is EXACT.')),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0, help_text='Documented in POLICY_SPEC.md Section 3 but not required for correctness in Week 1: explicit DENY always overrides ALLOW regardless of priority (Section 21), so this field is stored for future use / operator readability rather than consumed by the evaluation algorithm.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_scope', models.ForeignKey(help_text='The specific agent this policy applies to (POLICY_SPEC.md Section 5).', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='agents.agent')),
                ('task_scope', models.ForeignKey(help_text='The task this policy grants (or denies) authority within.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tasks.task')),
                ('tool_scope', models.ForeignKey(help_text='The single registered tool this policy applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tools.tool')),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['-priority', 'policy_id'],
                'indexes': [models.Index(fields=['task_scope', 'status'], name='policies_po_task_sc_6f2cf8_idx')],
            },
        ),
    ]
