# Generated by Django 5.2.7 on 2026-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
