# Generated by Django 5.2.7 on 2026-08-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_pending_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_id', models.SlugField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=200)),
                ('public_key_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mandate', to='commerce.purchaseintent')),
            ],
        ),
    ]
