# Generated by Django 5.2.7 on 2026-08-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_purchasemandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['merchant_id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(help_text='Which merchant this product belongs to. Nullable only until migration 0006 makes it required, after 0005 backfills existing rows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commerce.merchant'),
        ),
    ]
