# Generated by Django 5.2.7 on 2026-08-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('commerce', '0006_product_merchant_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(help_text='Which merchant this product belongs to. Nullable only until migration 0006 makes it required, after 0005 backfills existing rows.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commerce.merchant'),
        ),
        migrations.CreateModel(
            name='SpendingEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.SlugField(max_length=100, unique=True)),
                ('max_amount_minor', models.PositiveIntegerField()),
                ('remaining_amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spending_envelopes', to='agents.agent')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spending_envelopes', to='commerce.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'merchant', 'status'], name='commerce_sp_agent_i_d17f56_idx')],
            },
        ),
    ]
