# Generated by Django 5.2.7 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_product_merchant_spendingenvelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('CAPTURED', 'Captured'), ('RELEASED', 'Released')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='commerce.spendingenvelope')),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='envelope_debit', to='commerce.purchaseintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
